export const LOG_IN_SUCCEEDED = 'LOG_IN_SUCCEEDED';
export const LOG_OUT = 'LOG_OUT';

export const SAVE_CREDENTIALS = 'SAVE_CREDENTIALS';
export const UPDATE_PENDING_ITEMS = 'UPDATE_PENDING_ITEMS';
export const LOG_OUT_DONKEY = 'LOG_OUT_DONKEY';
export const FORCED_EJECTION = 'FORCED_EJECTION';
export const UPDATE_CONFIG_DATA = 'UPDATE_CONFIG_DATA';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const UPDATE_LOCALIZATION = 'UPDATE_LOCALIZATION';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const SAVE_LEFT_DRAWER_CONTEXT = 'SAVE_LEFT_DRAWER_CONTEXT';
export const SAVE_LOCATION_PREFERENCE = 'SAVE_LOCATION_PREFERENCE';

export const UPDATE_NOTES = 'UPDATE_NOTES';
export const UPDATE_POSTS = 'UPDATE_POSTS';
export const UPDATE_USER_POSTS = 'UPDATE_USER_POSTS';
export const UPDATE_LIKED_POSTS = 'UPDATE_LIKED_POSTS';
export const UPDATE_NEAR_ME_POSTS = 'UPDATE_NEAR_ME_POSTS';
export const UPDATE_FOLLOWING_POSTS = 'UPDATE_FOLLOWING_POSTS';
export const UPDATE_PINNED_POSTS = 'UPDATE_PINNED_POSTS';
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS';
export const UPDATE_FOLLOWING = 'UPDATE_FOLLOWING';
export const UPDATE_BLOCKED_PROFILES = 'UPDATE_BLOCKED_PROFILES';
