platform :ios, '12.1'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

project 'Discovrr',
  'Debug' => :debug,
  'Testing' => :debug,
  'Staging' => :release,
  'Release' => :release

target 'Discovrr' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  permission_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAlways', :path => "#{permission_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permission_path}/LocationWhenInUse"

  target 'DiscovrrTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper' => '0.98.0', 'Flipper-Folly' => '2.6.9' }, configurations: ['Debug', 'Testing'])

  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'FirebaseNotificationServiceExtension' do
  pod 'Firebase/Messaging', '~> 8.9.0'
end
